#district_name_
#palika_name_
#palika_code
#damge_grade_1-2_cnt
#damge_grade_3-5_cnt
#damage_total_cnt
#type_1_name
#type_1_palika_pct
#type_1_district_pct
#type_2_name
#type_2_palika_pct
#type_2_district_pct
#type_3_name
#type_3_palika_pct
#type_3_district_pct
#type_4_name
#type_4_palika_pct
#type_4_district_pct
#type_5_name
#type_5_palika_pct
#type_5_district_pct
#type_6_name
#type_6_palika_pct
#type_6_district_pct
#total_eligible_hhs_(reconstruction)
#pa_agreement_cnt_(reconstruction)
#1st_tranche_cnt_(reconstruction)
#2nd_tranche_cnt_(reconstruction)
#3rd_tranche_cnt_(reconstruction)
#houses_under_construction_cnt
#houses_completed_cnt
#total_eligible_hhs_(retrofit)
#pa_agreement_cnt_(retrofit)
#1st_tranche_cnt_(retrofit)
#2nd_tranche_cnt_(retrofit)
#grievances_registered_cnt
#grievances_addressed_cnt
#non_comp_registered_cnt
#non_comp_addressed_cnt
#active_pos_list
#phased_out_pos_list
#stone_required_quantity
#stone_availability
#stone_cost
#aggregate_required_quantity
#aggregate_availability
#aggregate_cost
#sand_required_quantity
#sand_availability
#sand_cost
#timber_required_quantity
#timber_availability
#timber_cost
#cement_ppc_required_quantity
#cement_ppc_availability
#cement_ppc_cost
#cement_opc_required_quantity
#cement_opc_availability
#cement_opc_cost
#rebar_required_quantity
#rebar_availability
#rebar_cost
#tin_required_quantity
#tin_availability
#tin_cost
#bricks_required_quantity
#bricks_availability
#bricks_cost
#types_of_workers_1
#avg_wage_skill
#types_of_workers_2
#avg_wage_labor
#schools_damaged_cnt
#school_completed_cnt
#schools_under_const_cnt
#health_posts_damaged_cnt
#_health_posts_completed_cnt
#health_posts_under_const_cnt
#contact_1_title
#contact_1_name
#contact_1_role
#contact_1_contact
#contact_2_title
#contact_2_name
#contact_2_role
#contact_2_contact
#contact_3_title
#contact_3_name
#contact_3_role
#contact_3_contact
#contact_4_title
#contact_4_name
#contact_4_role
#contact_4_contact
#contact_5_title
#contact_5_name
#contact_5_role
#contact_5_contact
#landless_cnt
#no_land_cert_cnt
#right_of_way_cnt
#hep_cnt
#small_plots_cnt
#guthi_land_cnt
#engineers_available_cnt
#engineers_req'd_cnt
#sub-engineers_available_cnt
#sub-engineers_req'd_cnt
#ass't_sub-engineers_available_cnt
#ass't_sub-engineers_req'd_cnt
#masons_7_day_available_cnt
#masons_7_day_req'd_cnt
#masons_50_day_available_cnt
#masons_50_day_req'd_cnt
#short_training_req'd_cnt
#short_training_reached_cnt
#short_training_remaining_cnt
#voc_training_req'd_cnt
#voc_training_reached_cnt
#voc_training_remaining_cnt
#number
#contact_1_name
#contact_1_title
#contact_1_number
#contact_2_name
#contact_2_title
#contact_2_number